## Importing numpy

In [5]:
import numpy as np

In [2]:
type([1,2,3])

list

## Converting List to Numpy array

In [17]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

## Attributes in Numpy

In [11]:
arr.shape  #Understanding shape of array

(3,)

In [12]:
arr.ndim

1

In [13]:
arr.size

3

In [14]:
arr.dtype

dtype('int64')

## Multidimensional Array to Numpy array

In [15]:
arr1=np.array([[1,2],[3,4]])

In [16]:
arr1

array([[1, 2],
       [3, 4]])

In [17]:
type(arr1)

numpy.ndarray

In [18]:
arr1.ndim

2

In [19]:
arr1.shape

(2, 2)

In [20]:
arr1.size

4

## Multidimesional Array of Different size gets treated differently

In [24]:
arr_n=np.array([[1,2],[3,4,5]])

/var/folders/4z/fkk_9s_s5g113y7pvfw8mkvw0000gn/T/ipykernel_81789/4148090161.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_n=np.array([[1,2],[3,4,5]])


In [25]:
arr_n

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [26]:
type(arr_n)

numpy.ndarray

In [27]:
type((1,2,3))

tuple

In [28]:
arr2=np.array((1,2,3))

In [29]:
type(arr2)

numpy.ndarray

In [30]:
arr2

array([1, 2, 3])

In [31]:
dict1={
'first_name':'shan' ,
'last_name':'singh'
}

In [32]:
type(dict1)

dict

In [33]:
result=dict1.items()

In [34]:
data=list(result)

In [37]:
arr3=np.array(data) # converts dict to a list of list or we can say nested list of multi dimensional list

In [38]:
arr3

array([['first_name', 'shan'],
       ['last_name', 'singh']], dtype='<U10')

In [39]:
arr3.shape

(2, 2)

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [42]:
arr1[:,1] # getting columns data for all the rows

array([2, 4])

In [44]:
arr1[0,:] #getting row data with including all the columns

array([1, 2])

## Indexing in Array

In [45]:
arr

array([1, 2, 3])

In [46]:
arr[1]

2

In [47]:
arr[2]

3

In [48]:
arr[-1]

3

In [37]:
arr[-2]

2

In [38]:
arr[-3]

1

In [39]:
arr[-4]

IndexError: index -4 is out of bounds for axis 0 with size 3

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr1[0][0]

1

In [42]:
arr1[0][1]

2

In [43]:
arr1[1][1]

4

## Some Numpy Type Casting

In [6]:
a1=np.array([1,5,6])

In [7]:
a1

array([1, 5, 6])

In [8]:
a1.dtype

dtype('int64')

In [9]:
a1_int16=np.array([1,5,6],dtype=np.int16)

In [10]:
a1_int16

array([1, 5, 6], dtype=int16)

In [11]:
a1_int64=np.array([1,5,6],dtype=np.int64)

In [12]:
a1_int64

array([1, 5, 6])

## Arithmatic Operation in Numpy


In [18]:
arr

array([1, 2, 3])

In [19]:
arr + 2

array([3, 4, 5])

In [20]:
arr + [2,2,2]

array([3, 4, 5])

In [21]:
np.add(arr,2)

array([3, 4, 5])

In [22]:
arr - 1

array([0, 1, 2])

In [23]:
arr - [1,1,1]

array([0, 1, 2])

In [24]:
np.subtract(arr,1)

array([0, 1, 2])

In [25]:
arr * 2

array([2, 4, 6])

In [26]:
arr * [2,2,2]

array([2, 4, 6])

In [27]:
np.multiply(arr,2)

array([2, 4, 6])

In [28]:
arr

array([1, 2, 3])

In [29]:
arr**2

array([1, 4, 9])

In [30]:
arr**3

array([ 1,  8, 27])

In [31]:
arr ** [2,2,2]

array([1, 4, 9])

In [32]:
np.power(arr,2)

array([1, 4, 9])

In [33]:
arr

array([1, 2, 3])

In [34]:
arr/2

array([0.5, 1. , 1.5])

In [35]:
arr%2

array([1, 0, 1])

In [36]:
arr // 2

array([0, 1, 1])

In [37]:
np.divide(arr,2)

array([0.5, 1. , 1.5])

In [38]:
np.divmod(arr,2)

(array([0, 1, 1]), array([1, 0, 1]))

## Statistical Functions in Numpy

In [39]:
l1=[1,2,3,4,5,6,6,7]

In [40]:
l1

[1, 2, 3, 4, 5, 6, 6, 7]

In [41]:
type(l1)

list

In [42]:
np.mean(l1)

4.25

In [43]:
np.median(l1)

4.5

In [44]:
l2=[1,2,3,4,5,6,6,7,600]

In [45]:
np.mean(l2)

70.44444444444444

In [46]:
np.median(l2)

5.0

In [47]:
np.var([1,2,3,4,5,6,6,7])

3.9375

In [48]:
np.std([1,2,3,4,5,6,6,7])

1.984313483298443

In [49]:
np.quantile([1,2,3,4,5,6,6,7],q=0.1)

1.7000000000000002

In [50]:
np.quantile([1,2,3,4,5,6,6,7],q=1)

7

## Creating 1D Array

In [51]:
np.linspace(1,10,10) #Linspace based upon last argument put equally distanced number of specified elements btw the given Intervals

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [52]:
np.arange(1,10.1,0.5) #Outputs a array of numbers with difference of last specifies arguments in btw the specified intervals 

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

## Creating 2D Numpy ARRAY

In [53]:
np.eye(5,5) #Populates the diagonals from Left to Right

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.ones((2, 3)) #Creates an array of all 1's 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.zeros((2, 3)) #Creates an array of all 0's

array([[0., 0., 0.],
       [0., 0., 0.]])

## Reshaping Array

In [56]:
a=np.array([[1,2,3],[4,5,6]])

In [57]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
type(a)

numpy.ndarray

In [59]:
a.shape

(2, 3)

In [60]:
a.reshape(3,2) #this is Row based rotation

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
a.reshape(3,2,order='F')

array([[1, 5],
       [4, 3],
       [2, 6]])

In [64]:
a.flatten(order='F') #flatten means to covert it into 1D, flatten works on anexisting numpy array

array([1, 4, 2, 5, 3, 6])

In [66]:
np.ravel(a).shape #This is a numpy package itself more faster than flatten

(6,)

In [62]:
a=[40,42,45,46,53,67,98,65]

In [63]:
a1=np.array(a)

In [64]:
np.where(a<50 , a/2 , a) # a is list here so where operation doesnt apply on it

TypeError: '<' not supported between instances of 'list' and 'int'

In [105]:
np.where(a1 < 50 , a1/2 , a1)

array([20. , 21. , 22.5, 23. , 53. , 67. , 98. , 65. ])